import {
	AppRunnerClient,
	CreateServiceCommand,
	DescribeServiceCommand,
	ListServicesCommand,
	StartDeploymentCommand,
} from '@aws-sdk/client-apprunner'

import type { DeployClient } from './types.ts'

export type AppRunnerOptions = {
	/** App Runner GitHub connection (`APPRUNNER_CONNECTION_ARN`, created once in the console) */
	connectionArn: string
	/** Instance role passed to the service (`APPRUNNER_INSTANCE_ROLE_ARN`), optional */
	instanceRoleArn?: string
	/** Polling for the service to leave `OPERATION_IN_PROGRESS` (default 15 min, 10 s apart) */
	timeoutMs?: number
	pollIntervalMs?: number
	now?: () => number
	sleep?: (ms: number) => Promise<void>
}

const defaultSleep = (ms: number) => new Promise<void>(resolve => setTimeout(resolve, ms))

/** Service names: 4–40 chars, letters/digits/dashes/underscores */
export const appRunnerServiceName = (name: string) =>
	name
		.replace(/[^A-Za-z0-9_-]/g, '-')
		.replace(/^-+/, '')
		.slice(0, 40)
		.padEnd(4, '0')

/**
 * Deploys the api of the pushed customer repo to App Runner from source: the repo's
 * `apprunner.yaml` (generated by `docs.ts`) is the build/run configuration. One service per
 * job; a second delivery of the same name starts a new deployment instead.
 */
export const createAppRunnerDeployClient = ({
	connectionArn,
	instanceRoleArn,
	timeoutMs = 15 * 60_000,
	pollIntervalMs = 10_000,
	now = Date.now,
	sleep = defaultSleep,
}: AppRunnerOptions): DeployClient => {
	const client = new AppRunnerClient({})

	const findService = async (serviceName: string) => {
		const { ServiceSummaryList } = await client.send(new ListServicesCommand({}))
		return ServiceSummaryList?.find(service => service.ServiceName === serviceName)
	}

	const waitUntilRunning = async (serviceArn: string) => {
		const deadline = now() + timeoutMs
		for (;;) {
			const { Service } = await client.send(new DescribeServiceCommand({ ServiceArn: serviceArn }))
			const status = Service?.Status
			if (status === 'RUNNING') return `https://${Service!.ServiceUrl}`
			if (status && status !== 'OPERATION_IN_PROGRESS') {
				throw new Error(`App Runner service ${serviceArn} is ${status}`)
			}
			if (now() >= deadline) {
				throw new Error(`App Runner service ${serviceArn} did not start in time`)
			}
			await sleep(pollIntervalMs)
		}
	}

	return {
		deployFromRepo: async ({ serviceName, repositoryUrl, branch }) => {
			const name = appRunnerServiceName(serviceName)
			const existing = await findService(name)
			if (existing?.ServiceArn) {
				await client.send(new StartDeploymentCommand({ ServiceArn: existing.ServiceArn }))
				return { url: await waitUntilRunning(existing.ServiceArn) }
			}
			const { Service } = await client.send(
				new CreateServiceCommand({
					ServiceName: name,
					SourceConfiguration: {
						AutoDeploymentsEnabled: false,
						AuthenticationConfiguration: { ConnectionArn: connectionArn },
						CodeRepository: {
							RepositoryUrl: repositoryUrl,
							SourceCodeVersion: { Type: 'BRANCH', Value: branch },
							CodeConfiguration: { ConfigurationSource: 'REPOSITORY' },
						},
					},
					InstanceConfiguration: {
						Cpu: '1024',
						Memory: '2048',
						InstanceRoleArn: instanceRoleArn,
					},
					HealthCheckConfiguration: { Protocol: 'HTTP', Path: '/health' },
					Tags: [{ Key: 'Service', Value: 'mf-delivery' }],
				})
			)
			if (!Service?.ServiceArn) throw new Error('App Runner CreateService returned no service')
			return { url: await waitUntilRunning(Service.ServiceArn) }
		},
	}
}

// MARK: Fakes

export type FakeDeploy = DeployClient & {
	deployments: { serviceName: string; repositoryUrl: string; branch: string }[]
}

export const createFakeDeployClient = (fail = false): FakeDeploy => {
	const fake: FakeDeploy = {
		deployments: [],
		deployFromRepo: async input => {
			if (fail) throw new Error('fake: App Runner deploy failed')
			fake.deployments.push(input)
			return {
				url: `https://${appRunnerServiceName(input.serviceName)}.eu-north-1.awsapprunner.com`,
			}
		},
	}
	return fake
}

export const createDryRunDeployClient = (log: (line: string) => void): DeployClient => ({
	deployFromRepo: async ({ serviceName, repositoryUrl, branch }) => {
		const name = appRunnerServiceName(serviceName)
		log(`[dry-run] app runner: create service ${name} from ${repositoryUrl}#${branch}`)
		return { url: `https://${name}.eu-north-1.awsapprunner.com` }
	},
})
